### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by yejinjian** [vuejs/vue-loader-example#22]
I am run "npm run build" after npm install without change any code, but:

ERROR in ./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
Module build failed: Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:603:19)
    at Object.fs.readFileSync (fs.js:438:24)
    at /data/app/vue-loader-example/node_modules/babel-loader/lib/helpers/read.js:21:45
    at find (/data/app/vue-loader-example/node_modules/babel-loader/lib/resolve-rc.js:23:12)
    at find (/data/app/vue-loader-example/node_modules/babel-loader/lib/resolve-rc.js:29:12)
    at module.exports (/data/app/vue-loader-example/node_modules/babel-loader/lib/resolve-rc.js:36:10)
    at Object.module.exports (/data/app/vue-loader-example/node_modules/babel-loader/index.js:44:11)
 @ ./src/app.vue 2:17-110

**Comment by thisconnect** [comment]
@yejinjian 
Windows does not know `export` change it to `SET`. [package.json#L8](https://github.com/vuejs/vue-loader-example/blob/3c77ef42ce3b92236ace09259924380bb48f0119/package.json#L8) for you should be
```
"build": "SET NODE_ENV=production && webpack --progress --hide-modules"
```
