### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by bobstar** [vuejs/vue-loader-example#34]
sorry,but I want to say,something musb be wrong of it.
I installed all ,and "npm run dev",but it most like hot-dev-server could't work .
maybe you should have a check, or maybe I did other things  wrong, Sorry for wasting your thime.

**Comment by lengziyu** [comment]
me too,
./~/babel-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/app.vue
Module build failed: Error: Cannot find module 'left-pad'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (E:\tests\vue\vue-loader\node_modules\babel-preset-es2015\node_modules\babel-plugin-transform-es2015-shorthand-properties\node_modules\babel-types\node_modules\babel-traverse\node_modules\babel-code-frame\node_modules\line-numbers\index.js:4:15)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
 @ ./src/app.vue 2:17-110 13:0-18:2 14:17-110，
右大哥，why?

**Comment by yyx990803** [comment]
What is your Node/npm version?

**Comment by lengziyu** [comment]
npm is 2.14.4,
Node 4.1.1,
Do I want to upgrade?

**Comment by q924053302** [comment]
我也遇到了和"lengziyu"同样的问题，我的npm版本是3.4.1，node是3.3.12

**Comment by yyx990803** [comment]
I tried npm 2 + node 4 & npm 3 + node 5, both works fine for me...
Most likely this is a bug in babel that has been fixed now. Try re-install all node modules and see if there's still an issue.
