### ISSUE TITLE
Something wrong with vue-loader which extracting CSS into a Single File

### ISSUE THREAD

**Issue by LeslieYQ** [vuejs/vue-loader-example#36]
I have download you example & npm install & npm install extract-text-webpack-plugin, editor webpack.config.js.

`````
var webpack = require('webpack'),
  ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: './src/main.js',
  output: {
    path: './dist',
    publicPath: 'dist/',
    filename: 'build.js'
  },
  module: {
    loaders: [{
      test: /\.vue$/,
      loader: 'vue'
    }, {
      // edit this for additional asset file types
      test: /\.(png|jpg|gif)$/,
      loader: 'file?name=[name].[ext]?[hash]'
    }]
  },
  vue: {
    loaders: {
      css: ExtractTextPlugin.extract("css"),
      stylus: ExtractTextPlugin.extract("css!stylus")
    }
  },

  // example: if you wish to apply custom babel options
  // instead of using vue-loader's default:
  babel: {
    presets: ['es2015', 'stage-0'],
    plugins: ['transform-runtime']
  },
  plugins: [
    new ExtractTextPlugin('[name].css')
  ]
}
``````

npm run build, then throw some error. like this:

``````
ERROR in ./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-d177eef6&file=app.vue!./~/stylus-loader!./~/vue-loader/lib/selector.js?type=style&index=0!./src/app.vue
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/yuqiu/Downloads/vue-loader-example-master/node_modules/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/app.vue 1:0-250

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-64d312f5&file=b.vue&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/b.vue
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/yuqiu/Downloads/vue-loader-example-master/node_modules/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/components/b.vue 1:0-260

ERROR in ./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~/css-loader!./~/vue-loader/lib/style-rewriter.js?id=_v-64c4fb74&file=a.vue&scoped=true!./~/vue-loader/lib/selector.js?type=style&index=0!./src/components/a.vue
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/Users/yuqiu/Downloads/vue-loader-example-master/node_modules/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/components/a.vue 1:0-260
````````

**Comment by yyx990803** [comment]
Make sure you didn't later overwrite `module.exports.plugins` in your webpack config.

**Comment by LeslieYQ** [comment]
yes, you're right. 

if (process.env.NODE_ENV === 'production') {
  module.exports.plugins = []
}

I always thought this‘s  extend, not  overwrite.

It's my  fault.

**Comment by LeslieYQ** [comment]
yes, you're right. 

if (process.env.NODE_ENV === 'production') {
  module.exports.plugins = []
}

I always thought this‘s  extend, not  overwrite.

It's my  fault.

thank you.
